[tool.dojo.world]
name = "colorit"
description = "Cairo variant of a popular puzzle game Flood Wars (https://play.google.com/store/apps/details?id=com.fva.flood.wars&hl=en_US)"
icon_uri = "file://assets/icon.png"

[package]
cairo-version = "2.4.0"
name = "colorit"
version = "0.4.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", version = "0.4.1" }
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/colorit/katana"
# Default account for katana with seed = 0
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
